name: Deploy to Production

on:
  push:
    branches:
      - develop_1

jobs:
  test:
    runs-on: ubuntu-latest  # Используем Ubuntu для тестов
    steps:
      - uses: actions/checkout@v3  # Клонируем репозиторий
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"  # Версия Python, которую используешь
      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          source venv/bin/activate
          python manage.py test

  deploy:
    needs: test  # Этот job запустится только если job 'test' успешно завершится
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}  # IP адрес сервера
          username: ${{ secrets.SSH_USER }} # Имя пользователя на сервере
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Приватный ключ SSH
          script: |
            ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
              cd /home/ubuntu/lms  # Путь к проекту на сервере (измени, если другой)
              git pull origin main  # Обновляем код
              python3.11 -m venv venv #Устанавливаем зависимости
              source venv/bin/activate
              pip install -r requirements.txt
              python manage.py migrate  # Выполняем миграции
              python manage.py collectstatic --noinput # Собираем статику
              sudo systemctl restart gunicorn # Перезапускаем Gunicorn
              sudo systemctl restart nginx # Перезапускаем Nginx
            '